name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 9.0.0
      - name: Setup pnpm and Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm turbo test
